### PR TITLE
Ng4t tests 2

### PR DESCRIPTION
**Pull request by dbeken85**
Changed the NAS Layer --> separated ESM/EMM layers.
Reviewed the code with Valgrind (Memcheck)
Implemented Congestion Handling
Implemented multi bearer / multi APN handover

### CODE REVIEW

**Comment by lionelgo** [comment]
Just some thoughts
In mme_app_context.c mme_create_new_ue_context():
  /*
   * Get 11 new bearers from the bearer pool.
   * They might or might not be pre-allocated.
   */
  for(uint8_t ebi = 5; ebi < 5 + MAX_NUM_BEARERS_UE -1; ebi++) {
    /** Insert 11 new bearers. */
    bearer_context_t * bearer_ctx_p = mme_app_new_bearer();
    DevAssert (bearer_ctx_p != NULL);
    bearer_ctx_p->ebi = ebi;
    RB_INSERT (BearerPool, &(new_p->bearer_pool), bearer_ctx_p);
  }

If you pre-allocate the bearers why not making just an array of (plain data) bearers, this would prevent memory fragmentation (cache)

**Comment by dbeken85** [comment]
> A small detail Why "<< 0" in common_defs.h:
> #define INTERNAL_FLAG_X2_HANDOVER (1 << 0)
> #define INTERNAL_FLAG_SKIP_RESPONSE (2 << 0)
> #define INTERNAL_FLAG_TRIGGERED_ACK (3 << 0)

You are right, I made a mistake. In my tests then they were always triggered.

**Comment by dbeken85** [comment]
> Just some thoughts
> In mme_app_context.c mme_create_new_ue_context():
> /*
> 
> * Get 11 new bearers from the bearer pool.
> * They might or might not be pre-allocated.
>   _/
>   for(uint8_t ebi = 5; ebi < 5 + MAX_NUM_BEARERS_UE -1; ebi++) {
>   /_* Insert 11 new bearers. */
>   bearer_context_t * bearer_ctx_p = mme_app_new_bearer();
>   DevAssert (bearer_ctx_p != NULL);
>   bearer_ctx_p->ebi = ebi;
>   RB_INSERT (BearerPool, &(new_p->bearer_pool), bearer_ctx_p);
>   }
> 
> If you pre-allocate the bearers why not making just an array of (plain data) bearers, this would prevent memory fragmentation (cache)

Thanks for the input!

I need to ask (I have not made much toughts about the issue of memory fragmentation):
Are you talking about allocating them all together? For example:   _`calloc(MAX_NUM_BEARERS, sizeof(bearer_context_t));`_

With the correct `__attribute__`'s, would it be possible to prevent memory fragmentation?

Or:

Are you talking about making it the old way? An array of bearers in the stack, no matter if they are allocated and not-allocated for a PDN session?
I think it would be not easy then to handle them in lists inside separete PDN contexts? I really would not prefer this option (and I had to rewrite everything).

If its the first one, I could look into it next week, when I start again working on the MME.

**Comment by lionelgo** [comment]
As a point of action, we have to do:
In EmmDeregisteredInitiated.c ;
//    todo: nas_delete_all_esm_procedures(emm_ctx);

**Comment by lionelgo** [comment]
> > Just some thoughts
> > In mme_app_context.c mme_create_new_ue_context():
> > /*
> > 
> > * Get 11 new bearers from the bearer pool.
> > * They might or might not be pre-allocated.
> >   _/
> >   for(uint8_t ebi = 5; ebi < 5 + MAX_NUM_BEARERS_UE -1; ebi++) {
> >   /_* Insert 11 new bearers. */
> >   bearer_context_t * bearer_ctx_p = mme_app_new_bearer();
> >   DevAssert (bearer_ctx_p != NULL);
> >   bearer_ctx_p->ebi = ebi;
> >   RB_INSERT (BearerPool, &(new_p->bearer_pool), bearer_ctx_p);
> >   }
> > 
> > If you pre-allocate the bearers why not making just an array of (plain data) bearers, this would prevent memory fragmentation (cache)
> 
> Thanks for the input!
> 
> I need to ask (I have not made much toughts about the issue of memory fragmentation):
> Are you talking about allocating them all together? For example: _`calloc(MAX_NUM_BEARERS, sizeof(bearer_context_t));`_
> 
> With the correct `__attribute__`'s, would it be possible to prevent memory fragmentation?
> 
> Or:
> 
> Are you talking about making it the old way? An array of bearers in the stack, no matter if they are allocated and not-allocated for a PDN session?
> I think it would be not easy then to handle them in lists inside separete PDN contexts? I really would not prefer this option (and I had to rewrite everything).
> 
> If its the first one, I could look into it next week, when I start again working on the MME.

I was thinking about the 2nd option, but don't rewrite everything for this kind of optimization unless you rewrite everything in C++ :-)

**Comment by dbeken85** [comment]
> > > Just some thoughts
> > > In mme_app_context.c mme_create_new_ue_context():
> > > /*
> > > 
> > > * Get 11 new bearers from the bearer pool.
> > > * They might or might not be pre-allocated.
> > >   _/
> > >   for(uint8_t ebi = 5; ebi < 5 + MAX_NUM_BEARERS_UE -1; ebi++) {
> > >   /_* Insert 11 new bearers. */
> > >   bearer_context_t * bearer_ctx_p = mme_app_new_bearer();
> > >   DevAssert (bearer_ctx_p != NULL);
> > >   bearer_ctx_p->ebi = ebi;
> > >   RB_INSERT (BearerPool, &(new_p->bearer_pool), bearer_ctx_p);
> > >   }
> > > 
> > > If you pre-allocate the bearers why not making just an array of (plain data) bearers, this would prevent memory fragmentation (cache)
> > 
> > 
> > Thanks for the input!
> > I need to ask (I have not made much toughts about the issue of memory fragmentation):
> > Are you talking about allocating them all together? For example: _`calloc(MAX_NUM_BEARERS, sizeof(bearer_context_t));`_
> > With the correct `__attribute__`'s, would it be possible to prevent memory fragmentation?
> > Or:
> > Are you talking about making it the old way? An array of bearers in the stack, no matter if they are allocated and not-allocated for a PDN session?
> > I think it would be not easy then to handle them in lists inside separete PDN contexts? I really would not prefer this option (and I had to rewrite everything).
> > If its the first one, I could look into it next week, when I start again working on the MME.
> 
> I was thinking about the 2nd option, but don't rewrite everything for this kind of optimization unless you rewrite everything in C++ :-)

I remember that we actually discussed this last summer. Handling bearers in multi bearer multi apn environment this way would be too tedious, so it's not a preferable option for me. But I will investigate the allocation of the bearer contexts in the heap with the memory analyser.

**Comment by dbeken85** [comment]
> As a point of action, we have to do:
> In EmmDeregisteredInitiated.c, EmmRegistered.c ;
> // todo: nas_delete_all_esm_procedures(emm_ctx);

I tought that the ESM layer always receives the detach indication, but nevertheless, I will review these todo's next week. Thank you very much.

**Comment by dbeken85** [comment]
> > > Just some thoughts
> > > In mme_app_context.c mme_create_new_ue_context():
> > > /*
> > > 
> > > * Get 11 new bearers from the bearer pool.
> > > * They might or might not be pre-allocated.
> > >   _/
> > >   for(uint8_t ebi = 5; ebi < 5 + MAX_NUM_BEARERS_UE -1; ebi++) {
> > >   /_* Insert 11 new bearers. */
> > >   bearer_context_t * bearer_ctx_p = mme_app_new_bearer();
> > >   DevAssert (bearer_ctx_p != NULL);
> > >   bearer_ctx_p->ebi = ebi;
> > >   RB_INSERT (BearerPool, &(new_p->bearer_pool), bearer_ctx_p);
> > >   }
> > > 
> > > If you pre-allocate the bearers why not making just an array of (plain data) bearers, this would prevent memory fragmentation (cache)
> > 
> > 
> > Thanks for the input!
> > I need to ask (I have not made much toughts about the issue of memory fragmentation):
> > Are you talking about allocating them all together? For example: _`calloc(MAX_NUM_BEARERS, sizeof(bearer_context_t));`_
> > With the correct `__attribute__`'s, would it be possible to prevent memory fragmentation?
> > Or:
> > Are you talking about making it the old way? An array of bearers in the stack, no matter if they are allocated and not-allocated for a PDN session?
> > I think it would be not easy then to handle them in lists inside separete PDN contexts? I really would not prefer this option (and I had to rewrite everything).
> > If its the first one, I could look into it next week, when I start again working on the MME.
> 
> I was thinking about the 2nd option, but don't rewrite everything for this kind of optimization unless you rewrite everything in C++ :-)

Hello Lionel,

After sleeping over it, I deleted my last answer, because I think that you are right with option a. It is a better solution. Stacked bearers as a bearer pool, where bearers also have link elements pointing to the next bearer of the pdn session, would work absolutely fine with lists, inside the pdn context (which also could be stacked).

I will also try out this option next week and give feedback. Thank's alot

**Comment by lionelgo** [comment]
Seems merging is blocked. Raphael can you make the process go ahead ?

**Comment by dbeken85** [comment]
> Seems merging is blocked. Raphael can you make the process go ahead ?

I will now start testing the MME again, might need to fix a bit. Please don't merge yet

**Comment by rdefosse** [comment]
Once again we have some difficulties cloning some GitHub repositories.

Is it possible to increase the tempo in the install/check scripts?

**Comment by bned-aeberlein** [comment]
On our CI, just like you, we initialize the submodules before starting the build, so the build scripts never fail while building the dependencies from GitHub submodule sources.
The only timeout we rarely get is when building the asn1c from source because we sometimes observe a short downtime there.
I don't see where exactly the error occurred in the dependency check in your Jenkins logs - but maybe this could be a hint.

**Comment by rdefosse** [comment]
I think I've resolved it.
See in the develop branch, the last commit I made:

```bash
git config --global https.postBuffer 123289600
```

and also I do up to 3 times the `git submodule update`

**Pull request merged**
